package jp.nephy.hypixelin.model.stats

import com.github.salomonbrys.kotson.*
import com.google.gson.JsonElement
import jp.nephy.hypixelin.converter.byList

class Arcade(val json: JsonElement) {
    val arrowsHitMiniWalls by json.byNullableInt("arrows_hit_mini_walls")
    val arrowsShotMiniWalls by json.byNullableInt("arrows_shot_mini_walls")
    val bountyHead by json.byNullableString("bounty_head")
    val bountyKillsOneinthequiver by json.byNullableInt("bounty_kills_oneinthequiver")
    val coins by json.byNullableFloat
    val deathsMiniWalls by json.byNullableInt("deaths_mini_walls")
    val deathsOneinthequiver by json.byNullableInt("deaths_oneinthequiver")
    val dec2016Achievements by json.byNullableBool("dec2016_achievements")
    val dec2016Achievements2 by json.byNullableBool("dec2016_achievements2")
    val enderspleefTrail by json.byNullableString("enderspleef_trail")
    val finalKillsMiniWalls by json.byNullableInt("final_kills_mini_walls")
    val goalsSoccer by json.byNullableInt("goals_soccer")
    val headshotsDayone by json.byNullableInt("headshots_dayone")
    val hitwRecordF by json.byNullableInt("hitw_record_f")
    val hitwRecordQ by json.byNullableInt("hitw_record_q")
    val killsDayone by json.byNullableInt("kills_dayone")
    val killsDragonwars2 by json.byNullableInt("kills_dragonwars2")
    val killsMiniWalls by json.byNullableInt("kills_mini_walls")
    val killsOneinthequiver by json.byNullableInt("kills_oneinthequiver")
    val maxWave by json.byNullableInt("max_wave")
    val meleeWeapon by json.byNullableString("melee_weapon")
    val miniwallsActivekit by json.byNullableString("miniwalls_activeKit")
    val monthlyCoinsA by json.byNullableInt("monthly_coins_a")
    val monthlyCoinsB by json.byNullableInt("monthly_coins_b")
    val packages by json.byList<String>()
    val poopCollected by json.byNullableInt("poop_collected")
    val roundsHoleInTheWall by json.byNullableInt("rounds_hole_in_the_wall")
    val roundsSimonSays by json.byNullableInt("rounds_simon_says")
    val stampLevel by json.byNullableInt("stamp_level")
    val swDeaths by json.byNullableInt("sw_deaths")
    val swEmpireKills by json.byNullableInt("sw_empire_kills")
    val swGameWins by json.byNullableInt("sw_game_wins")
    val swKills by json.byNullableInt("sw_kills")
    val swMonthlyKillsB by json.byNullableInt("sw_monthly_kills_b")
    val swWeeklyKillsA by json.byNullableInt("sw_weekly_kills_a")
    val timeStamp by json.byNullableLong("time_stamp")
    val weeklyCoinsA by json.byNullableInt("weekly_coins_a")
    val weeklyCoinsB by json.byNullableInt("weekly_coins_b")
    val winsDayone by json.byNullableInt("wins_dayone")
    val winsFarmHunt by json.byNullableInt("wins_farm_hunt")
    val winsGrinch by json.byNullableInt("wins_grinch")
    val winsMiniWalls by json.byNullableInt("wins_mini_walls")
    val winsParty by json.byNullableInt("wins_party")
    val winsParty2 by json.byNullableInt("wins_party_2")
    val winsParty3 by json.byNullableInt("wins_party_3")
    val winsSimonSays by json.byNullableInt("wins_simon_says")
    val witherDamageMiniWalls by json.byNullableInt("wither_damage_mini_walls")
    val witherKillsMiniWalls by json.byNullableInt("wither_kills_mini_walls")
}
