package jp.nephy.hypixelin.model.stats

import com.github.salomonbrys.kotson.byNullableBool
import com.github.salomonbrys.kotson.byNullableInt
import com.github.salomonbrys.kotson.byNullableString
import com.google.gson.JsonElement
import jp.nephy.hypixelin.converter.byList

class BedWars(val json: JsonElement) {
    val BedwarsOpenedchests by json.byNullableInt("Bedwars_openedChests")
    val BedwarsOpenedcommons by json.byNullableInt("Bedwars_openedCommons")
    val BedwarsOpenedrares by json.byNullableInt("Bedwars_openedRares")
    val Experience by json.byNullableInt
    val _itemsPurchasedBedwars by json.byNullableInt("_items_purchased_bedwars")
    val activeDeathCry by json.byNullableString
    val activeGlyph by json.byNullableString
    val activeKillEffect by json.byNullableString
    val activeVictoryDance by json.byNullableString
    val bedsBrokenBedwars by json.byNullableInt("beds_broken_bedwars")
    val bedsLostBedwars by json.byNullableInt("beds_lost_bedwars")
    val bedwarsBox by json.byNullableInt("bedwars_box")
    val bedwarsBoxCommons by json.byNullableInt("bedwars_box_commons")
    val bedwarsBoxRares by json.byNullableInt("bedwars_box_rares")
    val bedwarsBoxes by json.byNullableInt("bedwars_boxes")
    val bedwarsChristmasBoxes by json.byNullableInt("bedwars_christmas_boxes")
    val chestHistory by json.byNullableString("chest_history")
    val chestHistoryNew by json.byList<String>("chest_history_new")
    val coins by json.byNullableInt
    val deathsBedwars by json.byNullableInt("deaths_bedwars")
    val diamondResourcesCollectedBedwars by json.byNullableInt("diamond_resources_collected_bedwars")
    val _eightOneItemsPurchasedBedwars by json.byNullableInt("eight_one__items_purchased_bedwars")
    val eightOneBedsBrokenBedwars by json.byNullableInt("eight_one_beds_broken_bedwars")
    val eightOneBedsLostBedwars by json.byNullableInt("eight_one_beds_lost_bedwars")
    val eightOneDiamondResourcesCollectedBedwars by json.byNullableInt("eight_one_diamond_resources_collected_bedwars")
    val eightOneEmeraldResourcesCollectedBedwars by json.byNullableInt("eight_one_emerald_resources_collected_bedwars")
    val eightOneEntityAttackFinalDeathsBedwars by json.byNullableInt("eight_one_entity_attack_final_deaths_bedwars")
    val eightOneEntityAttackKillsBedwars by json.byNullableInt("eight_one_entity_attack_kills_bedwars")
    val eightOneFallFinalDeathsBedwars by json.byNullableInt("eight_one_fall_final_deaths_bedwars")
    val eightOneFinalDeathsBedwars by json.byNullableInt("eight_one_final_deaths_bedwars")
    val eightOneGamesPlayedBedwars by json.byNullableInt("eight_one_games_played_bedwars")
    val eightOneGoldResourcesCollectedBedwars by json.byNullableInt("eight_one_gold_resources_collected_bedwars")
    val eightOneIronResourcesCollectedBedwars by json.byNullableInt("eight_one_iron_resources_collected_bedwars")
    val eightOneItemsPurchasedBedwars by json.byNullableInt("eight_one_items_purchased_bedwars")
    val eightOneKillsBedwars by json.byNullableInt("eight_one_kills_bedwars")
    val eightOneLossesBedwars by json.byNullableInt("eight_one_losses_bedwars")
    val eightOnePermanentItemsPurchasedBedwars by json.byNullableInt("eight_one_permanent _items_purchased_bedwars")
    val eightOneResourcesCollectedBedwars by json.byNullableInt("eight_one_resources_collected_bedwars")
    val eightOneVoidKillsBedwars by json.byNullableInt("eight_one_void_kills_bedwars")
    val emeraldResourcesCollectedBedwars by json.byNullableInt("emerald_resources_collected_bedwars")
    val entityAttackDeathsBedwars by json.byNullableInt("entity_attack_deaths_bedwars")
    val entityAttackFinalDeathsBedwars by json.byNullableInt("entity_attack_final_deaths_bedwars")
    val entityAttackFinalKillsBedwars by json.byNullableInt("entity_attack_final_kills_bedwars")
    val entityAttackKillsBedwars by json.byNullableInt("entity_attack_kills_bedwars")
    val fallDeathsBedwars by json.byNullableInt("fall_deaths_bedwars")
    val fallFinalDeathsBedwars by json.byNullableInt("fall_final_deaths_bedwars")
    val fallFinalKillsBedwars by json.byNullableInt("fall_final_kills_bedwars")
    val fallKillsBedwars by json.byNullableInt("fall_kills_bedwars")
    val finalDeathsBedwars by json.byNullableInt("final_deaths_bedwars")
    val finalKillsBedwars by json.byNullableInt("final_kills_bedwars")
    val firstJoin7 by json.byNullableBool("first_join_7")
    val _fourFourItemsPurchasedBedwars by json.byNullableInt("four_four__items_purchased_bedwars")
    val fourFourBedsBrokenBedwars by json.byNullableInt("four_four_beds_broken_bedwars")
    val fourFourBedsLostBedwars by json.byNullableInt("four_four_beds_lost_bedwars")
    val fourFourDeathsBedwars by json.byNullableInt("four_four_deaths_bedwars")
    val fourFourDiamondResourcesCollectedBedwars by json.byNullableInt("four_four_diamond_resources_collected_bedwars")
    val fourFourEmeraldResourcesCollectedBedwars by json.byNullableInt("four_four_emerald_resources_collected_bedwars")
    val fourFourEntityAttackDeathsBedwars by json.byNullableInt("four_four_entity_attack_deaths_bedwars")
    val fourFourEntityAttackFinalDeathsBedwars by json.byNullableInt("four_four_entity_attack_final_deaths_bedwars")
    val fourFourEntityAttackFinalKillsBedwars by json.byNullableInt("four_four_entity_attack_final_kills_bedwars")
    val fourFourEntityAttackKillsBedwars by json.byNullableInt("four_four_entity_attack_kills_bedwars")
    val fourFourFallDeathsBedwars by json.byNullableInt("four_four_fall_deaths_bedwars")
    val fourFourFallFinalKillsBedwars by json.byNullableInt("four_four_fall_final_kills_bedwars")
    val fourFourFallKillsBedwars by json.byNullableInt("four_four_fall_kills_bedwars")
    val fourFourFinalDeathsBedwars by json.byNullableInt("four_four_final_deaths_bedwars")
    val fourFourFinalKillsBedwars by json.byNullableInt("four_four_final_kills_bedwars")
    val fourFourGamesPlayedBedwars by json.byNullableInt("four_four_games_played_bedwars")
    val fourFourGoldResourcesCollectedBedwars by json.byNullableInt("four_four_gold_resources_collected_bedwars")
    val fourFourIronResourcesCollectedBedwars by json.byNullableInt("four_four_iron_resources_collected_bedwars")
    val fourFourItemsPurchasedBedwars by json.byNullableInt("four_four_items_purchased_bedwars")
    val fourFourKillsBedwars by json.byNullableInt("four_four_kills_bedwars")
    val fourFourLossesBedwars by json.byNullableInt("four_four_losses_bedwars")
    val fourFourPermanentItemsPurchasedBedwars by json.byNullableInt("four_four_permanent _items_purchased_bedwars")
    val fourFourResourcesCollectedBedwars by json.byNullableInt("four_four_resources_collected_bedwars")
    val fourFourVoidDeathsBedwars by json.byNullableInt("four_four_void_deaths_bedwars")
    val fourFourVoidFinalDeathsBedwars by json.byNullableInt("four_four_void_final_deaths_bedwars")
    val fourFourVoidFinalKillsBedwars by json.byNullableInt("four_four_void_final_kills_bedwars")
    val fourFourVoidKillsBedwars by json.byNullableInt("four_four_void_kills_bedwars")
    val fourFourWinsBedwars by json.byNullableInt("four_four_wins_bedwars")
    val _fourThreeItemsPurchasedBedwars by json.byNullableInt("four_three__items_purchased_bedwars")
    val fourThreeBedsBrokenBedwars by json.byNullableInt("four_three_beds_broken_bedwars")
    val fourThreeBedsLostBedwars by json.byNullableInt("four_three_beds_lost_bedwars")
    val fourThreeDeathsBedwars by json.byNullableInt("four_three_deaths_bedwars")
    val fourThreeDiamondResourcesCollectedBedwars by json.byNullableInt("four_three_diamond_resources_collected_bedwars")
    val fourThreeEmeraldResourcesCollectedBedwars by json.byNullableInt("four_three_emerald_resources_collected_bedwars")
    val fourThreeEntityAttackDeathsBedwars by json.byNullableInt("four_three_entity_attack_deaths_bedwars")
    val fourThreeEntityAttackFinalDeathsBedwars by json.byNullableInt("four_three_entity_attack_final_deaths_bedwars")
    val fourThreeEntityAttackFinalKillsBedwars by json.byNullableInt("four_three_entity_attack_final_kills_bedwars")
    val fourThreeEntityAttackKillsBedwars by json.byNullableInt("four_three_entity_attack_kills_bedwars")
    val fourThreeFallKillsBedwars by json.byNullableInt("four_three_fall_kills_bedwars")
    val fourThreeFinalDeathsBedwars by json.byNullableInt("four_three_final_deaths_bedwars")
    val fourThreeFinalKillsBedwars by json.byNullableInt("four_three_final_kills_bedwars")
    val fourThreeGamesPlayedBedwars by json.byNullableInt("four_three_games_played_bedwars")
    val fourThreeGoldResourcesCollectedBedwars by json.byNullableInt("four_three_gold_resources_collected_bedwars")
    val fourThreeIronResourcesCollectedBedwars by json.byNullableInt("four_three_iron_resources_collected_bedwars")
    val fourThreeItemsPurchasedBedwars by json.byNullableInt("four_three_items_purchased_bedwars")
    val fourThreeKillsBedwars by json.byNullableInt("four_three_kills_bedwars")
    val fourThreeLossesBedwars by json.byNullableInt("four_three_losses_bedwars")
    val fourThreePermanentItemsPurchasedBedwars by json.byNullableInt("four_three_permanent _items_purchased_bedwars")
    val fourThreeResourcesCollectedBedwars by json.byNullableInt("four_three_resources_collected_bedwars")
    val fourThreeVoidDeathsBedwars by json.byNullableInt("four_three_void_deaths_bedwars")
    val fourThreeVoidFinalDeathsBedwars by json.byNullableInt("four_three_void_final_deaths_bedwars")
    val fourThreeVoidFinalKillsBedwars by json.byNullableInt("four_three_void_final_kills_bedwars")
    val fourThreeVoidKillsBedwars by json.byNullableInt("four_three_void_kills_bedwars")
    val fourThreeWinsBedwars by json.byNullableInt("four_three_wins_bedwars")
    val fourThreeWrappedPresentResourcesCollectedBedwars by json.byNullableInt("four_three_wrapped_present_resources_collected_bedwars")
    val freeEventKeyBedwarsChristmasBoxes2017 by json.byNullableBool("free_event_key_bedwars_christmas_boxes_2017")
    val gamesPlayedBedwars by json.byNullableInt("games_played_bedwars")
    val gamesPlayedBedwars1 by json.byNullableInt("games_played_bedwars_1")
    val goldResourcesCollectedBedwars by json.byNullableInt("gold_resources_collected_bedwars")
    val ironResourcesCollectedBedwars by json.byNullableInt("iron_resources_collected_bedwars")
    val itemsPurchasedBedwars by json.byNullableInt("items_purchased_bedwars")
    val killsBedwars by json.byNullableInt("kills_bedwars")
    val lossesBedwars by json.byNullableInt("losses_bedwars")
    val packages by json.byList<String>()
    val permanentItemsPurchasedBedwars by json.byNullableInt("permanent _items_purchased_bedwars")
    val quickjoinUsesRandom by json.byNullableInt("quickjoin_uses_random")
    val quickjoinUsesTotal by json.byNullableInt("quickjoin_uses_total")
    val resourcesCollectedBedwars by json.byNullableInt("resources_collected_bedwars")
    val sprayGlyphField by json.byNullableString("spray_glyph_field")
    val voidDeathsBedwars by json.byNullableInt("void_deaths_bedwars")
    val voidFinalDeathsBedwars by json.byNullableInt("void_final_deaths_bedwars")
    val voidFinalKillsBedwars by json.byNullableInt("void_final_kills_bedwars")
    val voidKillsBedwars by json.byNullableInt("void_kills_bedwars")
    val winsBedwars by json.byNullableInt("wins_bedwars")
    val winstreak by json.byNullableInt
    val wrappedPresentResourcesCollectedBedwars by json.byNullableInt("wrapped_present_resources_collected_bedwars")
}
